### ISSUE TITLE
Error optimize query

### ISSUE THREAD

**Issue by leogregianin** [ltworf/relational#11]
Attached the error to optimize query in single line mode.

![error](https://cloud.githubusercontent.com/assets/1684053/17281893/bda3624e-576d-11e6-887b-5c87caaa8a68.png)

**Comment by leogregianin** [comment]
I fixed this in commit 20ff424

**Comment by ltworf** [comment]
That's more like a bug in the windows terminal.

Does it do the same error if you start relational from the powershell?

**Comment by leogregianin** [comment]
In Powershell not the error occurs. You can close this issue.
