### ISSUE TITLE
Support in18n

### ISSUE THREAD

**Issue by allentiak** [ltworf/relational#12]
Hi,

Your project seems great. However, I don't see how to easily translate it into any other language.
It would be great if you could support some mechanism such as .po files (at least for the GUI), so people can help you support languages other than English. Maybe even Italian ? ;-)

Perhaps supporting QTLinguist might help? A similar project, PiReal uses it.
https://github.com/centaurialpha/pireal/

Best,
Leandro

**Comment by ltworf** [comment]
Hey, thank you.

I don't think I'll be implementing that soon.

The error messages you see come from the parser, which shouldn't be localised, so it would be necessary to provide several new kinds of exceptions and let the GUI display the appropriate error message.

Besides that, this is the list of contributors to this project: https://github.com/ltworf/relational/graphs/contributors

It's just me, so I don't have any expectation that anyone would provide a translation.

pireal is basically a fork of relational, I had considered using its GUI here, but it was crashing a lot, so in the end I didn't do it.
