### ISSUE TITLE
Implement essential keyboard shortcuts

### ISSUE THREAD

**Issue by semafor** [ltworf/relational#5]
(Forgive me if keyboard shortcuts have been implemented. If so, it should be documented at [1].)

Suggested shortcuts:

Context | Object | Key | Function
------------ | ------------- |  ------------- |  -------------
Relations | Relation | <kbd>Delete</kbd> | Unloads relation
Relations | Relation | <kbd>Enter</kbd> | Shows relation
History | Operation | <kbd>Delete</kbd> | Removes operation from history
Query |  | <kbd>Alt+o</kbd> | Inserts σ
Query |  | <kbd>Alt+p</kbd> | Inserts π
Query |  | <kbd>Alt+r</kbd> | Inserts ρ
Query |  | <kbd>Alt+m</kbd> | Inserts ➡
Query | Valid query | <kbd>Ctrl+Alt+o</kbd>, <kbd>Cmd+Alt+o</kbd> | Optimize
Query† | | <kbd>↑</kbd> | Previous operation (from history)\*
Query† | | <kbd>↓</kbd> | Next operation (from history)\*

† Single line mode

\* When using up/down arrows to traverse history, a query in the text field that has *not* been executed yet, should still be traversable. Meaning, if I write "π Fname, Lname " and press <kbd>↑</kbd>, I should be able to go back to my unfinished operation by pressing <kbd>↓</kbd> (just like in bash).

[1] http://ltworf.github.io/relational/allowed_expressions.html

**Comment by ltworf** [comment]
It's a valid suggestion, I think it shall be in the next release (If I manage to understand how to do that with Qt)

**Comment by ltworf** [comment]
I have been working on this.

I think I've found 2 or 3 bugs in Qt. :(

**Comment by ltworf** [comment]
I am hitting this bug: https://bugs.kde.org/show_bug.cgi?id=337491

And setting LANG=C causes a crash rather than showing a message with the error, and the text
```
Unhandled Python exception
Annullato
```

**Comment by ltworf** [comment]
I have opened a bug on KDE about this behaviour, that has been odd for about a decade

https://bugs.kde.org/show_bug.cgi?id=357418
