### ISSUE TITLE
"Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by franzribcek** [ltworf/relational#59]
Hi, I wanted to import a self-crafted csv file into relational, but get this error. It happens only with this specific file, although formatting and encoding type are the same as other files which I can successfully import as relations.

The file was produced with Excel, exported and edited to accomodate Relational necessities in this regard.

I'm on Windows 10.
[listino.CSV](https://github.com/ltworf/relational/files/7896596/listino.CSV)

**Comment by ltworf** [comment]
Mi sa che hai trovato un bug :)

It's trying to load it as json because the extension is upper case, renaming it to .csv instead of .CSV works (I tried)

You can do like that until I fix the issue.

**Comment by franzribcek** [comment]
> Mi sa che hai trovato un bug :)
> 
> It's trying to load it as json because the extension is upper case, renaming it to .csv instead of .CSV works (I tried)
> 
> You can do like that until I fix the issue.

The most frustrating one to find, too!

Grazie, comunque 😉
